[package]
name = "step-iso"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1" }
serde = { version = "1", features = ["derive"] }
borsh = { version = "1.5.3", features = ["derive"] }
itertools = "0.13.0"
committee-iso = { path = "../iso-committee" }
ssz_rs = { git = "https://github.com/jonas089/ssz-patched-crates" }
sha2 = "0.10.8"
sha2_sp1 = { package = "sha2", git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-sha2-v0.10.8", optional = true }

bls12_381 = { git = "https://github.com/zkcrypto/bls12_381", rev = "9ea427c0eb1a7e2ac16902a322aea156c496ddb0", features = [
    "experimental",
] }
bls12_381_sp1 = { package = "bls12_381", path = "../bls12_381", optional = true, features = [
    "experimental",
] }
sp1-derive = { workspace = true }
alloy-sol-types = "0.8.18"


[features]
sp1 = ["sha2_sp1", "bls12_381_sp1", "committee-iso/sp1"]
