
[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
serde_json = "1"
committee-iso = { path = "../iso-committee" }
step-iso = { path = "../iso-step" }
aggregate-iso = { path = "../iso-aggregate" }
preprocessor = { path = "../preprocessor" }
eth-types = { path = "../eth-types" }
aligned-sdk = { git = "https://github.com/yetanotherco/aligned_layer", tag = "v0.9.2" }
hex = "0.4.0"
rpassword = "7.3.1"
ssz_rs = { git = "https://github.com/jonas089/ssz-patched-crates" }
ethers = { tag = "v2.0.15-fix-reconnections", features = [
    "ws",
    "eip712",
], git = "https://github.com/yetanotherco/ethers-rs.git" }
tokio = { version = "1.40.0", features = ["full"] }
bincode = "1.3.3"
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.32" }
sp1-sdk = "3.4.0"
borsh = { version = "1.5.3", features = ["derive"] }
alloy-sol-types = "0.8.18"
reqwest = "0.12"
k256 = "0.13.4"
bls12_381 = { git = "https://github.com/zkcrypto/bls12_381", rev = "9ea427c0eb1a7e2ac16902a322aea156c496ddb0", features = [
    "experimental",
] }
itertools = "0.13.0"
ethereum-consensus-types = { git = "https://github.com/jonas089/ssz-patched-crates" }
beacon-api-client = { git = "https://github.com/jonas089/ssz-patched-crates" }


[build-dependencies]
sp1-helper = { workspace = true }

[features]
cuda = ["sp1-sdk/cuda"]
wrapped = []
